version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 321DIAblo!@#
      MYSQL_DATABASE: aggregation
  adminer:
    image: adminer
    restart: always
    ports:
      [9081:8080]
  wait-for-it:
    image: willwill/wait-for-it
    entrypoint: "./wait-for-it.sh -t 300 db:3306 --strict"
  aggregation:
    build: .
    ports:
      [9082:8081]
    depends_on:
      - db
    restart: on-failure
